/* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception */
#define __ai static __inline__ __attribute__((__always_inline__, __nodebug__))
#define __aio static __inline__ __attribute__((__always_inline__, __nodebug__, __overloadable__))

__ai __attribute__((__clang_arm_builtin_alias(__builtin_sve_svadd_n_s32_m)))
svint32_t svadd_n_s32_m(svbool_t, svint32_t, int32_t);
__aio __attribute__((__clang_arm_builtin_alias(__builtin_sve_svadd_n_s32_m)))
svint32_t svadd_m(svbool_t, svint32_t, int32_t);

__ai __attribute__((__clang_arm_builtin_alias(__builtin_sve_svadd_s32_m)))
svint32_t svadd_s32_m(svbool_t, svint32_t, svint32_t);
__aio __attribute__((__clang_arm_builtin_alias(__builtin_sve_svadd_s32_m)))
svint32_t svadd_m(svbool_t, svint32_t, svint32_t);

__aio __attribute__((__clang_arm_builtin_alias(__builtin_sve_reinterpret_s8_s8)))
svint8_t svreinterpret_s8_s8(svint8_t op);
__aio __attribute__((__clang_arm_builtin_alias(__builtin_sve_reinterpret_s8_s8)))
svint8_t svreinterpret_s8(svint8_t op);

__ai __attribute__((__clang_arm_builtin_alias(__builtin_sve_svprobe_u32)))
svuint32_t svprobe_u32(unsigned int, void const *);

__ai __attribute__((__clang_arm_builtin_alias(__builtin_sve_internal_probe)))
__builtin_fake_t __builtin_sve_internal_probe(__builtin_fake_t);

/*
 * Modification notice: this reduced test fixture is derived from the arm_sve.h
 * resource header generated by llvm/llvm-project release llvmorg-22.1.1 at
 * commit fef02d48c08db859ef83f84232ed78bd9d1c323a and was modified for test use
 * with synthetic probe declarations.
 */
