/* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception */
#define __ai static __inline__ __attribute__((__always_inline__, __nodebug__))

__ai __attribute__((target("neon"))) int32x4_t vaddq_s32(int32x4_t __p0, int32x4_t __p1) {
__ai __attribute__((target("neon"))) int32x4_t __noswap_vaddq_s32(int32x4_t __p0, int32x4_t __p1) {
#define vld1q_s32(__p0) __extension__ ({ __builtin_neon_vld1q_s32(__p0); })

/*
 * Modification notice: this reduced test fixture is derived from the arm_neon.h
 * resource header generated by llvm/llvm-project release llvmorg-22.1.1 at
 * commit fef02d48c08db859ef83f84232ed78bd9d1c323a and was modified for test use
 * with a synthetic helper declaration and shortened macro.
 */
