/* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception */
#define __ai static __inline__ __attribute__((__always_inline__, __nodebug__))
#define __aio static __inline__ __attribute__((__always_inline__, __nodebug__, __overloadable__))

__ai __attribute__((__clang_arm_builtin_alias(__builtin_sme_svmopa_za32_s8_m)))
void svmopa_za32_s8_m(uint64_t, svbool_t, svbool_t, svint8_t, svint8_t);
__aio __attribute__((__clang_arm_builtin_alias(__builtin_sme_svmopa_za32_s8_m)))
void svmopa_za32_m(uint64_t, svbool_t, svbool_t, svint8_t, svint8_t);

__ai __attribute__((__clang_arm_builtin_alias(__builtin_sme___arm_in_streaming_mode)))
bool __arm_in_streaming_mode(void);

__ai __attribute__((target("sme"))) void svundef_za(void) __arm_streaming_compatible __arm_out("za") {

/*
 * Modification notice: this reduced test fixture is derived from the arm_sme.h
 * resource header generated by llvm/llvm-project release llvmorg-22.1.1 at
 * commit fef02d48c08db859ef83f84232ed78bd9d1c323a and was modified for test use.
 */
