/* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception */

static __inline__ __attribute__((__clang_arm_builtin_alias(__builtin_arm_mve_vaddq_n_s32)))
int32x4_t __arm_vaddq_n_s32(int32x4_t, int32_t);
static __inline__ __attribute__((__overloadable__, __clang_arm_builtin_alias(__builtin_arm_mve_vaddq_n_s32)))
int32x4_t __arm_vaddq(int32x4_t, int32_t);
static __inline__ __attribute__((__clang_arm_builtin_alias(__builtin_arm_mve_vaddq_n_s32)))
int32x4_t vaddq_n_s32(int32x4_t, int32_t);
static __inline__ __attribute__((__overloadable__, __clang_arm_builtin_alias(__builtin_arm_mve_vaddq_n_s32)))
int32x4_t vaddq(int32x4_t, int32_t);

static __inline__ __attribute__((__clang_arm_builtin_alias(__builtin_arm_mve_vcvtq_s16_f16)))
int16x8_t __arm_vcvtq_s16_f16(float16x8_t);
static __inline__ __attribute__((__clang_arm_builtin_alias(__builtin_arm_mve_vcvtq_s16_f16)))
int16x8_t vcvtq_s16_f16(float16x8_t);

static __inline__ __attribute__((__overloadable__, __clang_arm_builtin_alias(__builtin_arm_mve_vuninitializedq_polymorphic_s32)))
int32x4_t __arm_vuninitializedq(int32x4_t);
static __inline__ __attribute__((__overloadable__, __clang_arm_builtin_alias(__builtin_arm_mve_vuninitializedq_polymorphic_s32)))
int32x4_t vuninitializedq(int32x4_t);

/*
 * Modification notice: this reduced test fixture is derived from the arm_mve.h
 * resource header generated by llvm/llvm-project release llvmorg-22.1.1 at
 * commit fef02d48c08db859ef83f84232ed78bd9d1c323a and was modified for test use.
 */
